import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from pathlib import Path
from datetime import datetime

from app.database import get_db
from app import models, schemas
from app.auth import get_current_user
from app.email_utils.sender import send_email_with_attachment
from app.rendering.pdf_renderer import render_resume_pdf
from app.rendering.renderer import contact_info_from_user

router = APIRouter(prefix="/tailored-outputs", tags=["tailored-outputs"])


def _role_from_tailored_json(tailored_json: str) -> str:
    try:
        tj = json.loads(tailored_json)
        if isinstance(tj, dict):
            jr = tj.get("job_requirements")
            if isinstance(jr, dict) and jr.get("role"):
                return jr["role"]
    except Exception:
        pass
    return ""


def _normalize_tailored(tj) -> dict:
    """Recover proper resume sections when an LLM echo stored the whole input
    payload (older/buggy outputs): prefer top-level, fall back to full_resume.
    Also maps parser aliases (management_and_leadership_skills) -> leadership."""
    if not isinstance(tj, dict):
        return {}
    aliases = {"management_and_leadership_skills": "leadership"}
    base = tj.get("full_resume") if isinstance(tj.get("full_resume"), dict) else {}
    out = {}
    for key in ("summary_heading", "summary", "skills",
                "experience", "projects", "education",
                "certifications", "leadership"):
        val = tj.get(key) or base.get(key)
        if not val:
            for alias, canonical in aliases.items():
                if key == canonical and (tj.get(alias) or base.get(alias)):
                    val = tj.get(alias) or base.get(alias)
        if val:
            out[key] = val
    return out


_SECTION_ALIASES = {"management_and_leadership_skills": "leadership"}


def _normalize_resume(tj: dict) -> dict:
    """Rename parser alias keys to canonical section names (top-level only)."""
    out = dict(tj)
    for alias, canonical in _SECTION_ALIASES.items():
        if alias in out and not out.get(canonical):
            out[canonical] = out[alias]
    return out


def _merge_from_source(output, tj: dict, db) -> dict:
    """Fill empty sections of an old/partial output from its source resume."""
    if db is None:
        return tj
    resume = db.query(models.Resume).filter(models.Resume.id == output.resume_id).first()
    if not resume:
        return tj
    try:
        src = json.loads(resume.resume_json)
    except Exception:
        return tj
    if not isinstance(src, dict):
        return tj
    src = _normalize_resume(src)
    result = dict(tj)
    for key in ("summary", "skills", "experience", "projects",
                "education", "certifications", "leadership"):
        if not result.get(key) and src.get(key):
            result[key] = src[key]
    return result


def _resolve_pdf_path(output, current_user, db=None) -> str:
    """Prefer the PDF generated by the pipeline; otherwise render one on the
    fly from the stored tailored JSON so old outputs also download as PDF."""
    if output.docx_path:
        sibling = Path(output.docx_path).with_suffix(".pdf")
        if sibling.exists():
            return str(sibling)
    try:
        tj = json.loads(output.tailored_json)
    except Exception:
        tj = {}
    tj = _normalize_tailored(tj)
    tj = _merge_from_source(output, tj, db)
    contact_info = contact_info_from_user(
        current_user,
        title=_role_from_tailored_json(output.tailored_json),
    )
    return render_resume_pdf(tj, f"resume_{output.id}.pdf", contact_info)


def _output_error(tailored_json: str) -> str | None:
    """Recover a stored error message from a failed output's tailored_json."""
    try:
        tj = json.loads(tailored_json)
        if isinstance(tj, dict) and tj.get("error"):
            return str(tj["error"])
    except Exception:
        pass
    return None


def _to_out(output, db: Session) -> schemas.TailoredOutputOut:
    message = db.query(models.Message).filter(
        models.Message.tailored_output_id == output.id
    ).order_by(models.Message.created_at.desc()).first()
    return schemas.TailoredOutputOut(
        id=output.id,
        job_post_id=output.job_post_id,
        resume_id=output.resume_id,
        status=output.status,
        docx_path=output.docx_path,
        tailored_json=output.tailored_json,
        draft_message=message.draft_text if message else None,
        error=_output_error(output.tailored_json),
    )


def _verify_ownership(output, current_user: models.User, db: Session) -> None:
    """Ensure the tailored output belongs to the current user (prevents IDOR)."""
    job_post = db.query(models.JobPost).filter(models.JobPost.id == output.job_post_id).first()
    if not job_post or job_post.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Not found")


def _require_ready(output) -> None:
    """Downloads/sending are only valid once the pipeline finished."""
    if output.status in {"ready", "approved", "sent"}:
        return
    if output.status == "failed":
        raise HTTPException(
            status_code=409,
            detail=f"Tailoring failed: {_output_error(output.tailored_json) or 'unknown error'}",
        )
    raise HTTPException(
        status_code=409,
        detail=f"Output is still being tailored (status '{output.status}'). "
               "Poll GET /tailored-outputs/{id} and try again when it is 'ready'.",
    )


@router.get("", response_model=list[schemas.TailoredOutputOut])
def list_tailored_outputs(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    outputs = (
        db.query(models.TailoredOutput)
        .join(models.JobPost, models.JobPost.id == models.TailoredOutput.job_post_id)
        .filter(models.JobPost.user_id == current_user.id)
        .order_by(models.TailoredOutput.created_at.desc())
        .all()
    )
    return [_to_out(output, db) for output in outputs]


@router.get("/{output_id}", response_model=schemas.TailoredOutputOut)
def get_tailored_output(
    output_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Polled by the extension popup ('Ready — view in app') and by the
    web app's approval screen."""
    output = db.query(models.TailoredOutput).filter(models.TailoredOutput.id == output_id).first()
    if not output:
        raise HTTPException(status_code=404, detail="Not found")
    _verify_ownership(output, current_user, db)

    return _to_out(output, db)


@router.get("/{output_id}/download")
def download_resume(
    output_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    output = db.query(models.TailoredOutput).filter(models.TailoredOutput.id == output_id).first()
    if not output:
        raise HTTPException(status_code=404, detail="Not found")
    _verify_ownership(output, current_user, db)

    # Pipeline must have finished (ready/approved/sent), otherwise there is
    # nothing to render — fail with a clear message instead of an empty PDF.
    _require_ready(output)

    try:
        pdf_path = _resolve_pdf_path(output, current_user, db=db)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"Could not render PDF: {e}")

    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename="tailored_resume.pdf",
    )


@router.post("/{output_id}/approve")
def approve_output(
    output_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Human-in-the-loop approval gate (blueprint 3.7) — required before
    the Sender module (3.8) is allowed to send anything."""
    output = db.query(models.TailoredOutput).filter(models.TailoredOutput.id == output_id).first()
    if not output:
        raise HTTPException(status_code=404, detail="Not found")
    _verify_ownership(output, current_user, db)

    _require_ready(output)

    output.status = "approved"
    db.commit()
    return {"status": "approved"}


@router.post("/{output_id}/send")
def send_output(
    output_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Send the approved tailored resume via email (blueprint 3.8).
    Transitions TailoredOutput.status → 'sent' and Message.status → 'sent'.
    Sends from the user's OWN Gmail when their profile has SMTP credentials
    (per-user sending, nothing hardcoded); falls back to .env SMTP_*."""
    output = db.query(models.TailoredOutput).filter(models.TailoredOutput.id == output_id).first()
    if not output:
        raise HTTPException(status_code=404, detail="Not found")
    _verify_ownership(output, current_user, db)

    if output.status != "approved":
        raise HTTPException(
            status_code=400,
            detail=f"Output is '{output.status}', not 'approved'. Approve first via POST /tailored-outputs/{output_id}/approve.",
        )

    # Fetch the associated message (draft text)
    message = db.query(models.Message).filter(
        models.Message.tailored_output_id == output.id
    ).order_by(models.Message.created_at.desc()).first()
    if not message:
        raise HTTPException(status_code=404, detail="No draft message found for this output.")

    # Use the already-generated PDF, else the DOCX path from the pipeline.
    try:
        attachment_path = _resolve_pdf_path(output, current_user, db=db)
    except Exception:
        attachment_path = output.docx_path if output.docx_path and Path(output.docx_path).exists() else None
    if not attachment_path or not Path(attachment_path).exists():
        raise HTTPException(
            status_code=404,
            detail=f"Generated attachment not found at {attachment_path}. Pipeline may have failed.",
        )

    # Send the email. Preferred path: Gmail API (OAuth) from the user's own
    # connected Gmail — no password needed. Fall back to SMTP + App Password
    # (per-user, else shared .env) if Gmail API isn't connected/configured.
    try:
        from app.email_utils.gmail_api import send_via_gmail_api

        sent_via_gmail = send_via_gmail_api(
            user=current_user,
            to_email=current_user.email,
            subject=f"Your tailored resume for job post {output.job_post_id}",
            body=message.draft_text,
            attachment_path=attachment_path,
        )
    except RuntimeError as gmail_err:
        # Gmail API not connected/configured -> fall back to SMTP + App Password.
        try:
            send_email_with_attachment(
                to_email=current_user.email,
                subject=f"Your tailored resume for job post {output.job_post_id}",
                body=message.draft_text,
                attachment_path=attachment_path,
                smtp_username=current_user.smtp_username,
                smtp_app_password=current_user.smtp_app_password,
            )
            sent_via_gmail = False
        except RuntimeError as e:
            hint = (
                "To send without a password, connect Gmail once in your profile "
                "(Gmail API OAuth). Otherwise set an App Password in your profile "
                "or in .env SMTP_*."
            )
            raise HTTPException(
                status_code=400,
                detail=f"Email sending failed: {e} ({gmail_err}) — {hint}",
            )

    # Update statuses in DB
    output.status = "sent"
    message.status = "sent"
    message.sent_at = datetime.utcnow()
    db.commit()

    return {"status": "sent", "sent_at": message.sent_at.isoformat()}
