"""initial schema

Revision ID: da564220095d
Revises: 
Create Date: 2026-09-25 18:07:53.017984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da564220095d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('capabilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'term', name='uq_user_term')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capabilities_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_bytes', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('doc_json', sa.JSON(), nullable=True),
    sa.Column('coverage_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_sha256', 'version', name='uq_resume_version')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index('ix_resume_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_sha256', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=True),
    sa.Column('index_json', sa.JSON(), nullable=True),
    sa.Column('standing_json', sa.JSON(), nullable=True),
    sa.Column('ops_json', sa.JSON(), nullable=True),
    sa.Column('accepted_json', sa.JSON(), nullable=True),
    sa.Column('rejected_json', sa.JSON(), nullable=True),
    sa.Column('tailored_json', sa.JSON(), nullable=True),
    sa.Column('diff_json', sa.JSON(), nullable=True),
    sa.Column('outreach_json', sa.JSON(), nullable=True),
    sa.Column('proof_json', sa.JSON(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('call_log_json', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_run_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_jd_sha256'), ['jd_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stage', name='uq_artifact_stage')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('confirm_token_hash', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_run_id'), ['run_id'], unique=False)

    op.create_table('op_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('op_id', sa.String(length=64), nullable=False),
    sa.Column('op_kind', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_feedback_run_id'), ['run_id'], unique=False)

    op.create_table('run_checkpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stage', name='uq_checkpoint_stage')
    )
    with op.batch_alter_table('run_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_checkpoints_run_id'), ['run_id'], unique=False)

    op.create_table('send_audit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('attachment_hash', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_audit_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_audit_message_id'))

    op.drop_table('send_audit')
    with op.batch_alter_table('run_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_checkpoints_run_id'))

    op.drop_table('run_checkpoints')
    with op.batch_alter_table('op_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_feedback_run_id'))

    op.drop_table('op_feedback')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_run_id'))

    op.drop_table('messages')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_resume_id'))
        batch_op.drop_index(batch_op.f('ix_runs_jd_sha256'))
        batch_op.drop_index('ix_run_user_created')

    op.drop_table('runs')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_status'))
        batch_op.drop_index(batch_op.f('ix_resumes_file_sha256'))
        batch_op.drop_index('ix_resume_user_status')

    op.drop_table('resumes')
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_user_id'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capabilities_user_id'))

    op.drop_table('capabilities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))

    op.drop_table('users')
    # ### end Alembic commands ###
